# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-states-formation-terragrunt"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "environments/dev/vpc/terraform.tfstate"
    region         = "eu-west-1"
  }
}
